CREATE TABLE trip_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    destination VARCHAR(120) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    notes VARCHAR(2000),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT trip_plans_date_range_check CHECK (end_date >= start_date)
);

CREATE TABLE daily_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    route_date DATE NOT NULL,
    title VARCHAR(120) NOT NULL,
    notes VARCHAR(2000),
    route_color VARCHAR(7) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT daily_routes_color_check CHECK (route_color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT daily_routes_plan_date_unique UNIQUE (trip_plan_id, route_date)
);

CREATE INDEX trip_plans_updated_at_index ON trip_plans (updated_at DESC);
CREATE INDEX daily_routes_plan_date_index ON daily_routes (trip_plan_id, route_date);
