CREATE TABLE route_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_route_id BIGINT NOT NULL REFERENCES daily_routes(id) ON DELETE CASCADE,
    google_place_id VARCHAR(255) NOT NULL,
    name VARCHAR(200) NOT NULL,
    formatted_address VARCHAR(500),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT route_points_latitude_check CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT route_points_longitude_check CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT route_points_sort_order_check CHECK (sort_order >= 0),
    CONSTRAINT route_points_route_place_unique UNIQUE (daily_route_id, google_place_id),
    CONSTRAINT route_points_route_order_unique UNIQUE (daily_route_id, sort_order)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX route_points_daily_route_order_index
    ON route_points (daily_route_id, sort_order);
