CREATE TABLE navigation_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_route_id BIGINT NOT NULL REFERENCES daily_routes(id) ON DELETE CASCADE,
    origin_point_id BIGINT NOT NULL REFERENCES route_points(id) ON DELETE CASCADE,
    destination_point_id BIGINT NOT NULL REFERENCES route_points(id) ON DELETE CASCADE,
    travel_mode VARCHAR(16) NOT NULL,
    option_id VARCHAR(80) NOT NULL,
    route_payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT navigation_selections_segment_unique
        UNIQUE (daily_route_id, origin_point_id, destination_point_id),
    CONSTRAINT navigation_selections_points_differ
        CHECK (origin_point_id <> destination_point_id),
    CONSTRAINT navigation_selections_mode_check
        CHECK (travel_mode IN ('WALK', 'DRIVE', 'TRANSIT'))
);

CREATE INDEX navigation_selections_daily_route_index
    ON navigation_selections (daily_route_id);
